### ISSUE TITLE
FFMPEG Process never be killed  with RTSP Stream

### ISSUE THREAD

**Issue by giboow** [kokorin/Jaffree#269]
**Describe the issue**
I use FFMPEG to transform RSTP stream, from survey camera, into mp4 file to be displayed into a webpage. Sometime ffmpeg take long time to process, then I want to stop the ffmpeg process.

**To Reproduce**
This is how I generate a FFmpegResultFuture
```java
FFmpeg ffmpeg = FFmpeg.atPath();
if (realTime) {
    ffmpeg.addArgument("-re");
}
ffmpeg
        .addArguments("-rtsp_transport", "tcp")
        .addArguments("-i", url)
        .addArguments("-loglevel","debug")
        .addArguments("-vcodec", "copy")
        .addArguments("-movflags", "empty_moov+delay_moov")
        .addOutput(PipeOutput.pumpTo(os)
                .disableStream(StreamType.AUDIO)
                .disableStream(StreamType.SUBTITLE)
                .disableStream(StreamType.DATA)

                .setFrameRate(0.1)
                .setFormat("mp4"))
        .addArgument("-nostdin");

return ffmpeg.executeAsync();
```

Then how i use it :
```java
FFmpegResultFuture ffmpegFuture = null;

try {
    ffmpegFuture = hikVisionService.streamOutputstreamWithParams(
            os, camera, rtspUriParams
    );
  
    ffmpegFuture.get(20, TimeUnit.SECONDS);
} catch (InterruptedException | ExecutionException | TimeoutException e) {
    log.error("livestream, event {}: {} => {}", id, e.getClass().getSimpleName(), e.getMessage());
        ffmpegFuture.forceStop();
}
```

When I use my debugger, I can see the process execute the code contained into FFmpegStopper class, but the ffmpeg process isn't stopped (I can see it in my Terminal with `ps -fax | grep ffmpeg` command.
I've tried it on my Apple Laptop and with an Ubuntu 21.10 distribution, then I have the same problem.

Is it viable to kill the process on the forceStop method?
```java
@Override
public void forceStop() {
    sendToStdIn("qq");
    process.destroy();
}
```

**Comment by kokorin** [comment]
First of all MP4 does not support streaming. With `PipeOutput` you will get corrupted file (because seeking is required to finalize mp4 tables).

Also I recommend using `UrlInput` instead of specifying all input parameters as arbitrary arguments.

> Is it viable to kill the process on the forceStop method?

Yes, you can do that, but output mp4 could be corrupted (because ffmpeg won't finalize writings).

To investigate the issue further logs are required. Please provide logs for successful and unsuccessful scenarios. You can set log level reported by ffmpeg itself with [FFmpeg#setLogLevel](https://github.com/kokorin/Jaffree/blob/4fad6383105adf2cd44b9eb6f824b0f3f0b94a3c/src/main/java/com/github/kokorin/jaffree/ffmpeg/FFmpeg.java#L372).  For message to appear in SLF4J logging it's required to configure appropriate log level for SLF4J.

**Comment by giboow** [comment]
Thanks for all your recommendations.

The ` .addArgument("-nostdin") command block the kill process. I have deleted it, and It works!
No need to kill the process

Sorry for the mistake.
