### ISSUE TITLE
0.8.2: metadata read problem

### ISSUE THREAD

**Issue by Emmenemoi** [kokorin/Jaffree#46]
com.github.kokorin.jaffree.ffprobe.Stream.getTag() is empty for video stream having metadata.
ex:
```
Stream #0:0(und): Video: hevc (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 7709 kb/s, 29.97 fps, 29.97 tbr, 600 tbn, 600 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2019-03-18T07:54:08.000000Z
      handler_name    : Core Media Data Handler
      encoder         : HEVC
    Side data:
      displaymatrix: rotation of -90.00 degrees
```

getTag() had "rotate" metadata in tag list before (version 0.8.0).

Now we must rely only on getSideDataList() -> x.getRotation() for video rotation detection (then real width / height after ffmpeg conversion).

Not sure this is universal.

**Comment by kokorin** [comment]
@Emmenemoi Please, provide an example project (with content file) for reproduction.
Also the major change in 0.8.1 was introduction of  FormatParser for ffprobe output.
Try to switch from FlatFormatParser to DefaultFormatParser with FFprobe.setFormat()

**Comment by kokorin** [comment]
@Emmenemoi I have reproduced. Tags are not available on Stream indeed because of switch to FlatFormatParser. FFprobe output in default format uses singular TAG to name corresponding section, while flat format uses plural forms: TAGS.
I will try to find some time this weekend to test that nothing else was touched.

Right now you have several options:
1. Use DefaultFormatParser 
2. Extract tags from stream manually: `stream.getSection().getTag("TAGS").getValues(DTag.TAG_CONVERTER);`

**Comment by Emmenemoi** [comment]
The stream.getSection().getTag("TAGS") is null

**Comment by kokorin** [comment]
@Emmenemoi check 0.8.3, I have published changes to read `rotate` tag for both parsers.
