### ISSUE TITLE
Maven version is still on Oct

### ISSUE THREAD

**Issue by eos1d3** [kokorin/Jaffree#6]
I found Maven version 0.3 is dated Oct. Is current change significant to update to a newer version? 

Thanks!

**Comment by kokorin** [comment]
Do you mean not published to maven version? Or just want to know if it worths to update from 0.2 to 0.3? The latter l was [published](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.kokorin.jaffree%22%20AND%20a%3A%22jaffree%22)  on 24-Aug-2017.

0.3 mainly contains changes for programmatic video production and consumption (see [examples](https://github.com/kokorin/Jaffree/tree/master/examples/src/main/java)). But also it contains some bug fixes. As a general rule you should use the latest version.

0.4 is aimed at support of NUT container format instead of MP4 for programmatic video production and consumption.

0.4-SNAPSHOT in master branch contains some cherry picks, so if you need that build you can either clone repository and build it locally, or you can use [jitpack](https://jitpack.io/#kokorin/jaffree) (notice Commits tab)

**Comment by eos1d3** [comment]
Right, I meant why there is no 0.4 maven version as I do not want to download and include it manually.

Knowning 0.4 aimed at support of NUT only, I will keep using 0.3 for a while. Thanks!

**Comment by kokorin** [comment]
Well, since this project is OSS and my personal, I develop it in my free time and when I feel interest. I will review any pull request (or feedback) with pleasure. 

Could you also be so kind and share in which project you use Jaffree?

**Comment by kokorin** [comment]
I have release 0.4 to Maven Central.
