### ISSUE TITLE
How can i handle errors in ffprobe or ffmpeg? 

### ISSUE THREAD

**Issue by tarikkilic** [kokorin/Jaffree#97]
I run ffprobe and got streams data: 

`        FFprobeResult result = ffprobe
                .setShowStreams(true)
                .setInput(this.streamPath)
                .execute();
      for (Stream stream : result.getStreams()) {
            StreamInfoDto streamInfoDto = new StreamInfoDto();
            streamInfoDto.setCodecType(stream.getCodecType().code());
            streamInfoDto.setBitrate(stream.getBitRate());
....
`

For example I want to handle error like 'No such file or directory' . FFprobeResult has error object but i couldn't use them. 
Does not go to next line after execute function. Stopped. 

Second Question:

It never ends when I give a invalid udp URL.  How can I put timeout?

Thanks

**Comment by kokorin** [comment]
Jaffree throwns an exception if ffmpeg or ffprobe process ends with non-zero code. You need to catch an exception thrown in `execute()`. Check [FFprobeTest](/kokorin/Jaffree/blob/master/src/test/java/com/github/kokorin/jaffree/ffprobe/FFprobeTest.java)


```
@Test
public void testExceptionIsThrownIfFfprobeExitsWithError() {
    expectedException.expect(new StackTraceMatcher("No such file or directory"));
    FFprobeResult result = FFprobe.atPath(BIN)
            .setInput(Paths.get("nonexistent.mp4"))
            .execute();
}
```

Regarding UDP it's probably by design. If you run ffprobe or ffmpeg with command line manually and they don't exit - check available UDP options in ffmpeg documentations.
It's possible to stop ffprobe/ffmpeg executed by `Jaffree` with Thread interruption. You can find examples in README.

**Comment by tarikkilic** [comment]
Thank for answer.
